import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import BillCard from "@/components/BillCard";
import WeekCard from "@/components/WeekCard";
import Menu from "@/components/Menu";

export default function Home() {
  return (
    <>
      <Head>
        <title>broke</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-row justify-between bg-gradient-to-b from-[#ffffff] to-[#c4c4c4]">
        <div
          id="menu"
          className="flex w-2/12 flex-col gap-4 bg-black p-4 text-white"
        >
          <Menu />
        </div>
        <div id="calendar" className="w-8/12 p-4">
          calendar
        </div>

        <div id="itinerary" className="flex w-3/12 flex-col gap-1 p-4">
          <WeekCard />
          <BillCard />
        </div>
      </main>
    </>
  );
}
